4 chat room
LearnTeachCode/babble pull request #11
Opened 2017-03-02 05:56 UTC by austin-simmons

It's a very bare-bones and ugly chat REPL... but you can chat with yourself at least!

2017-03-06 17:51 UTC, armaneous requested changes

2017-03-06 17:51 UTC, armaneous commented on .gitignore
> +tags
Add `.vscode`, please (we're also going to need to clean it up from the repo, but I can do that)

2017-03-06 17:51 UTC, x2adrew commented on devrequirements.txt
> +pylint==1.6.5
Did you branch off of `aa-dev-setup`? There shouldn't be a `devrequirements.txt` file. Please merge `dev` into your branch and remove excess/duplicate files.

2017-03-06 17:51 UTC, x2adrew commented on main.py
> +  app.listen(8000)
Any reason for the port number change?

2017-03-06 17:51 UTC, x2adrew commented on main.py
> +      (r'/chatsock$', ChatSocket)
What does `$` mean in this context?

2017-03-06 17:51 UTC, x2adrew commented on devrequirements.txt
> +pylint==1.6.5
Wait, I just saw `requirements.txt` below. Please just remove this file.

2017-03-06 17:52 UTC, x2adrew commented
Sorry! I started the review earlier this week, but forgot I had to submit from the top right after adding all the comments. Bit of a learning curve getting used to this GitHub review format.

2017-03-07 02:10 UTC, austin-simmons commented on .gitignore
> +tags
added it to the .gitignore, should be removed now

2017-03-07 02:11 UTC, austin-simmons commented on devrequirements.txt
> +pylint==1.6.5
removed the devrequirements.txt, I commited it accidentally when switching from my dev-setup branch to dev

2017-03-07 04:03 UTC, armaneous approved these changes

2017-03-07 04:05 UTC, kammitama5 approved these changes
looks good.

2017-03-07 04:06 UTC, merged