profile amended files
LearnTeachCode/babble pull request #6
Opened 2017-02-19 16:34 UTC by kammitama5

the updated files (two-> profile.html and profile.py) are in the folder 5-krystal-dev-setup. I included the original files..not sure if I should just be pushing over the two changed files. I can always just push the two files as the only files if need be. Thanks.

2017-02-20 03:29 UTC, autto91 requested changes

2017-02-20 03:29 UTC, austin-simmons commented on profile.html
> +    <link rel="stylesheet" href="style.css">
You might want to change to use the {{ static_url }} variable for tornado.

2017-02-20 03:30 UTC, x2adrew commented on 5-krystal-dev-setup/profile.py
> +		self.email = email
Only bare minimum required for creating a profile, so that means you don't `phonenumber` by default

2017-02-20 03:30 UTC, x2adrew commented on 5-krystal-dev-setup/profile.py
> +		self.username = user1
We're not allowing users to change their usernames, we shouldn't need this.

2017-02-20 03:30 UTC, x2adrew commented on 5-krystal-dev-setup/profile.py
> +		self.phonenumber = phone1
Use the Python properties decorator, given as an example here: http://stackoverflow.com/a/2627034/2045446
Specifically, we need to be able to get and set the phone number.

Also, please use more purposeful names as `phone1` doesn't mean much. Maybe something like `new_number`?

2017-02-20 03:30 UTC, x2adrew commented on profile.html
> +<!DOCTYPE html>
This file should be in `/templates`

2017-02-20 03:30 UTC, x2adrew commented on 5-krystal-dev-setup/profile.py
> +        #print self.username, "<" + self.email + ">"
We don't need this, let's not add code/comment clutter

2017-02-20 03:30 UTC, x2adrew commented on 5-krystal-dev-setup/profile.py
> +
For every property a user will be able to edit, we should apply getters and setters to, the Pythonic way (reference the link above)

2017-02-28 04:12 UTC, x2adrew commented
Closing this pull request, please pull into dev

2017-02-28 04:12 UTC, closed without merging